Test high risk pipeline

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,3 +21,9 @@ jobs:
 
       - name: Build Project
         run: mvn clean package
+
+      - name: Run Unit Tests
+        run: |
+          echo "Running tests..."
+          echo "Tests failed"
+          exit 1
